language: java


# Use Java 8
jdk:
  - oraclejdk8

# Cache Maven Dependencies
cache:
  directories:
  - $HOME/.m2


# Use container-based infrastructure
sudo: false


before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
# Communicate with Octopull
  - "[ \"$BUILD_PR_BRANCH\" = \"true\" ] && git checkout $TRAVIS_BRANCH && echo \"OCTOPULL_SHA=$(git rev-parse HEAD)\"; true"

env:
  - BUILD_PR_BRANCH=true
  - BUILD_PR_BRANCH=false
matrix:
  allow_failures:
    - env:
      - BUILD_PR_BRANCH=true
after_script:
  - echo "== CHECKSTYLE_RESULT ==" && cat "target/checkstyle-result.xml" && echo "== END_CHECKSTYLE_RESULT =="
  - echo "== PMD_RESULT ==" && cat "target/pmd.xml" && echo "== END_PMD_RESULT =="
  - echo "== FINDBUGS_RESULT ==" && cat "target/findbugsXml.xml" && echo "== END_FINDBUGS_RESULT =="


# setting the Slack email notification level to none

notifications:

  slack: semteam9:Zrf7NDsECoPyuR05XePB0EtV

  email: false
  webhooks:
    - http://octopull.rmhartog.me/api/travis/webhook
