language: java

# Build using Maven, running test suites
script: mvn test

# setting the Slack email notification level to none

notifications:

  slack: semteam9:Zrf7NDsECoPyuR05XePB0EtV

  email: false